apiVersion: v1
kind: Service
metadata:
  name: hello-gitlab-ci
  namespace: default
spec:
  type: NodePort
  selector:
    app: hello-gitlab-ci
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5005
      nodePort: 32005
