apiVersion: v1
kind: Service
metadata:
  name: smb-timemachine
spec:
  selector:
    app: smb-timemachine
  ports:
    - name: netbios
      protocol: TCP
      port: 139
      targetPort: 139
      nodePort: 30139
    - name: smb
      protocol: TCP
      port: 445
      targetPort: 445
      nodePort: 30445
  type: NodePort
